package pl.rmalinowski.adhocmanager.events;

public enum PhysicalLayerEventType {
	
	ADAPTER_NOT_ENABLED,
	CONNECTING_TO_NEIGHBOURS_FINISHED,
	CONNECTION_TO_NEIGHBOUR_ESTABLISHED,
	CONNECTION_TO_NEIGHBOUR_NOT_ESTABLISHED,
	CONNECTION_TO_NEIGHBOUR_LOST,
	PACKET_RECEIVED,
	PACKET_SEND,
	PHYSICAL_LAYER_INITIALIZED,
	NEW_NODE_ADDED,
	TOAST
}
