package pl.rmalinowski.adhocmanager.model;

public enum PhysicalLayerEventType {
	
	BLUETOOTH_NOT_ENABLED,
	CONNECTING_TO_NEIGHBOURS_FINISHED,
	CONNECTION_TO_NEIGHBOUR_ESTABLISHED,
	CONNECTION_TO_NEIGHBOUR_LOST,
	DATA_PACKET_RECEIVED,
	DATA_PACKET_SEND,
	PHYSICAL_LAYER_INITIALIZED
}
